#!/bin/bash
#
#  Compare networks and components in PCB generated by NetGen and as modified by KiCad after manual routing.
#  The NetGen pcbs are in modules directory, KiCad pcbs are in goodpcbs.
#
#   $1 = pcb name, eg, aluboard
#
d=`dirname $0`
CLASSPATH=$d/classes java ParsePCB < ../goodpcbs/$1.pcb | sed 's/1[.]2K/1.0K/g' > $1.goodpcb.parsed
CLASSPATH=$d/classes java ParsePCB < ../modules/$1.pcb > $1.module.parsed
diff $1.module.parsed $1.goodpcb.parsed > $1.diff
